infinilabs/framework

modules/elastic/common/domain.go
adding field Request to record metric request statement, and then we can show the metric request statement in UI
=> feat: adding field `Request` to record metric request statement

lib/fasthttp/http.go
This pull request introduces a new method to the `Request` struct in the `lib/fasthttp/http.go` file to validate the request's host. The most important change is the addition of the `Validate` method, which checks if the host is non-nil and non-empty.
Validation addition:
* [`lib/fasthttp/http.go`](diffhunk://#diff-1c2282f696a8d7b10894fbfafaf37111fbb6987425398978674f801c57cd6021R2169-R2176): Added a `Validate` method to the `Request` struct to ensure the host is present and non-empty.
=> feat: add util to validate request

core/task/task.go
Fix warning: `
Call of 'task.RegisterScheduleTask' copies the lock value: type 'task.ScheduleTask' contains 'atomic.Bool' contains 'interface{}' which is 'sync.Locker' 
`
This warning is a result of Go’s strict handling of types containing atomic fields or synchronization primitives (e.g., sync.Locker). When such types are copied, it can cause subtle bugs because the copied value shares access to underlying synchronization mechanisms or memory.
This pull request includes changes to the `core/task/task.go` file to improve the handling of the `isTaskRunning` field in task structures. The changes ensure that `isTaskRunning` is properly initialized as a pointer to an `atomic.Bool`.
Initialization improvements:
* [`core/task/task.go`](diffhunk://#diff-2f9f5c5794e6f62c51694839d6a1f5731f6ea782569 …
=> fix: avoid copy atomic value

app.go, docs/content.en/docs/release-notes/_index.md
=> chore: trim spaces from input variables during app initialization

Makefile
You will see some error like this:
```
➜  gateway git:(main) ✗ OFFLINE_BUILD=true make build               
cat: /Users/medcl/go/src/infini.sh/framework/.latest_commit_hash.txt: No such file or directory
```
Why This Happens?
Make evaluates $(shell ...) while parsing the Makefile to substitute the result into the command list. For example, in this line:
The $(shell cat ...) is evaluated as soon as Make parses the Makefile. If the file .latest_commit_hash.txt does not exist at this point, you’ll see the error.
The file .latest_commit_hash.txt does not yet exist when $(shell ...) is evaluated. This leads to the error.
In this PR,  we remove shell, and fixed the error.
=> fix: remove shell usage to prevent missing file error in Makefile

docs/content.en/docs/release-notes/_index.md, modules/queue/disk_queue/consumer.go
Previously, the process would halt if more than one gap was encountered, requiring manual intervention. This fix allows seamless progression to the next file, even when multiple gaps are present, improving workflow efficiency.
=> fix: enable skipping to the next file with multiple gaps

docs/content.en/docs/release-notes/_index.md, modules/metrics/elastic/elasticsearch.go
removing the logic of collecting metric per each node
=> fix: removing the logic of collecting metric per each node

docs/content.en/docs/release-notes/_index.md, modules/elastic/common/domain.go
add `min_bucket_size` and `hits_total` to metric configurations
=> feat: add `min_bucket_size` and `hits_total` to metric configurations

docs/content.en/docs/release-notes/_index.md, lib/fasthttp/request_context.go
=> fix: parse password from basic auth

core/api/client.go, core/config/system.go, core/env/env.go, core/env/http_client.go, docs/content.en/docs/references/http_client.md, docs/content.en/docs/release-notes/_index.md, modules/configs/client/client.go
Closes https://github.com/infinilabs/framework/issues/32
This PR introduces the ability to configure proxy settings for the HTTP client, enabling seamless operation in environments with network access restrictions. If your App or HTTP requests requires a proxy for network access, you can leverage this feature to configure proxy settings as follows:
```
http_client:
default:
proxy:
enabled: true
default_config:
http_proxy: http://127.0.0.1:7890
socket5_proxy: socks5://127.0.0.1:7890
override_system_proxy_env: true # Override system proxy environment settings
permitted:
- "google.com"
denied:
- "localhost"
- "infinilabs.com"
- "api.coco.rs"
domains:
"github.com":
http_proxy: http://127.0.0.1:7890
socket5_proxy: socks5://127.0.0.1:7890
custom_profile:
proxy:
enabled: false
```
=> feat: add proxy settings to  config section

modules/elastic/metadata.go, modules/metrics/metrics.go
fix metrics collection after cluster recovery from unavailability
=> fix: metrics collection after cluster recovery from unavailability

modules/api/api.go
perform system cluster health check only when it is set up, fix #39
=> fix: perform system cluster health check only when it is set up

core/env/env.go, docs/content.en/docs/release-notes/_index.md
=> chore: fix invalid data folder, remove cluster_config and use appname directly for configuration

Makefile
This pull request includes changes to the `Makefile` in the `package-windows-platform` to improve the testing process. The most important change is the addition of a configuration step before running tests and the restoration of a generated file after tests are run.
Changes to the testing process:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L327-R330): Modified the `test` target to include a `config` step before running tests, added verbose flag `-v` to `$(GOTEST)`, and included a step to restore a generated file after tests are run.
=> test: for ci test

Makefile
ci code lint for pr
This pull request includes changes to the `Makefile` to enhance the build and testing processes by introducing a linting step and improving the configuration of the `GOTEST` command.
Improvements to build and testing processes:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L77-R78): Modified the `GOTEST` command to use the `APP_NEED_CGO` variable for the `CGO_ENABLED` setting, ensuring consistent behavior based on the application's CGO requirements.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R332-R334): Added a new `GOLINT` command to enable linting with `go vet`, and introduced a `lint` target to the makefile to run this command.
=> ci: for code lint

core/api/handler.go, docs/content.en/docs/release-notes/_index.md
add util to http handler, support write bytes with status code
This pull request includes changes to improve the handling of HTTP responses and updates to the release notes documentation. The most important changes include refactoring the `WriteJSON` method to use a new `WriteBytes` method, and updating the release notes to reflect the new utility added to the HTTP handler.
Improvements to HTTP response handling:
* [`core/api/handler.go`](diffhunk://#diff-d7ecb439c9f4ce5dc7fc00d000ce3579ac2666a18054b58cb27ff126d745f30eL163-R178): Refactored the `WriteJSON` method to use a new `WriteBytes` method for writing byte arrays with a status code. This change ensures that the header is written only once.
Documentation updates:
* [`docs/content.en/docs/release-notes/_index.md`](diffhunk://#diff-6a5a …
=> feat: add util to http handler, support write bytes with status code 

docs/content.en/docs/release-notes/_index.md
release notes
This pull request updates the release notes for the INFINI Framework in the `docs/content.en/docs/release-notes/_index.md` file. The changes include adding new sections for breaking changes, features, bug fixes, and improvements, as well as updating the release notes for version 1.1.0 and version 1.0.0 with specific dates.
Release notes updates:
* Added new sections for breaking changes, features, bug fixes, and improvements under the "Latest (In development)" section.
* Updated the release notes for version 1.1.0 with the release date "2025-01-11" and included a breaking change regarding the WebSocket greeting message header.
* Removed duplicate breaking changes entry for version 1.1.0.
* Updated the release notes for version 1.0.0 with the release date "2024-12-13".
=> chore: update release notes for v1.1.0

modules/elastic/module.go
Enable metadata_refresh by default 
This pull request to `modules/elastic/module.go` includes changes to enable metadata refresh and add logging for Elasticsearch metadata updates. The most important changes are:
Metadata refresh configuration:
* [`modules/elastic/module.go`](diffhunk://#diff-fa0cefecf570cf5b4cfbc279b6c12092a20e53726d4a79bcb9aa285f1c52d575L70-R71): Enabled metadata refresh by setting `Enabled` to `true` and changed the `Interval` from "10s" to "30s" in the `MetadataRefresh` configuration.
Logging improvements:
* [`modules/elastic/module.go`](diffhunk://#diff-fa0cefecf570cf5b4cfbc279b6c12092a20e53726d4a79bcb9aa285f1c52d575R688-R690): Added a trace log statement to log Elasticsearch metadata updates in the `refreshAllClusterMetadata` function.
=> chore: enable metadata_refresh by default

docs/content.en/docs/release-notes/_index.md, modules/queue/disk_queue/consumer.go
Fixes: https://github.com/infinilabs/gateway/issues/49
This pull request includes changes to improve the handling of message reads for partially loaded files and updates to the release notes documentation. The most important changes include improvements to the handling of invalid message reads in the `disk_queue` consumer and updates to the release notes for better clarity.
Improvements to handling of message reads:
* [`modules/queue/disk_queue/consumer.go`](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b2ba2L313-R332): Improved handling of invalid message reads by differentiating between dirty reads and partial file loads, and added appropriate logging and statistics increments. [[1]](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f …
=> refactor: improve handling of message read for partially loaded files

core/orm/mapper.go, core/orm/mapper_test.go, core/orm/orm.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/orm.go
This PR introduces improvements to the search functionality, addressing its current simplicity and lack of optimization for performance.
Key Changes:
- Custom Mapper Functionality: Search results can now be parsed using a user-defined mapper function, enabling more flexible and tailored result handling.
- Future Performance Enhancements: This sets the groundwork for low-level search operations to return raw bytes directly to the mapper, reducing processing overhead and improving performance.
By implementing these changes, we aim to provide better extensibility and prepare for advanced optimizations in upcoming iterations.
=> feat: add new search function to orm module, support result item mapper

docs/content.en/docs/release-notes/_index.md, plugins/badger/api.go, plugins/badger/module.go
This PR introduces a new API to retrieve the top N keys from a Badger DB, with sorting options based on either the key size or count. The API enhances the ability to quickly analyze key statistics and prioritize the most significant keys based on custom criteria.
- New API Endpoint:
- A new API endpoint is added: `GET /badger/stats`, which returns the top N keys from the Badger DB.
- This endpoint accepts the following query parameters:
- `size`: The number of top keys to retrieve (default is 10).
- `sort`: The sorting criteria, which can be size (sort by value size) or count (sort by key count).
- Efficient Key Retrieval:
- The API uses a read-only transaction to iterate over all keys in the Badger DB.
- For each key, the size and count are tracked and stored.
- The top N keys are sorted …
=> feat:  add new stats api to quickly find the top N keys from a Badger DB

core/elastic/view.go
add `complex_fields` field for `View` struct
=> feat: add `complex_fields` field for `View` struct

docs/content.en/docs/release-notes/_index.md, modules/elastic/common/config.go, modules/elastic/module.go
=> feat: proactively restore dead node's availability

core/elastic/view.go
add field 'Builtin' to struct 'View'
=> feat: add field 'Builtin' to struct 'View'

docs/content.en/docs/release-notes/_index.md, modules/queue/disk_queue/consumer.go
This pull request includes a small but important change to the `modules/queue/disk_queue/consumer.go` file. The change ensures that the read position is reset to the previous position when an invalid message size is detected, which helps to handle partial file loads more gracefully.
* [`modules/queue/disk_queue/consumer.go`](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b2ba2R331): Added a line to reset `d.readPos` to `previousPos` when an invalid message size is detected, improving the handling of partial file loads.
=> fix: reload file need use privious pos

core/util/bytes.go, core/util/bytes_test.go, docs/content.en/docs/release-notes/_index.md, modules/queue/disk_queue/cleanup.go, modules/queue/disk_queue/consumer.go, modules/queue/disk_queue/module.go, plugins/elastic/bulk_indexing/bulk_indexing.go
This pull request includes several updates and improvements across multiple files. The changes primarily involve enhancing logging messages for better clarity, adding error handling, and updating function implementations. Below are the most important changes grouped by theme:
* Updated various logging messages in `modules/queue/disk_queue/consumer.go` to include more detailed information, such as `workerID`. This improves traceability and debugging. [[1]](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b2ba2L205-R215) [[2]](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b2ba2L250-R252) [[3]](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b2ba2R261) …
=> fix: unsafe method panic, reduce log, slice work with id

docs/content.en/docs/release-notes/_index.md, modules/configs/config/config.go, modules/configs/config/config_test.go
This pull request includes changes to the `SaveConfigStr` function in the `modules/configs/config/config.go` file to improve error handling and ensure the configuration directory exists before saving the configuration file.
Improvements to error handling and directory creation:
* Added a check to create the configuration directory if it does not exist before attempting to save the configuration file. (`modules/configs/config/config.go`, [modules/configs/config/config.goR140-R144](diffhunk://#diff-fdd202f68b86524d47407f638491e1572f1bd25aff830b81da035279798d0c64R140-R144))
* Removed unnecessary blank line for cleaner code. (`modules/configs/config/config.go`, [modules/configs/config/config.goL122](diffhunk://#diff-fdd202f68b86524d47407f638491e1572f1bd25aff830b81da035279798d0c64L122))
=> fix: create file before put content to it

core/api/api.go, core/host/process_info.go, core/util/netutils.go, docs/content.en/docs/release-notes/_index.md
This pull request includes changes to centralize and standardize the use of network address constants across the codebase. The most important changes include the introduction of new constants for reserved and local addresses, and the replacement of hardcoded address strings with these constants.
Centralization and standardization of network address constants:
* [`core/util/netutils.go`](diffhunk://#diff-3fa3772b0e7ad87ab2978e874a2324cafde5cedf6d5f4e6b810520f1b44a4320R38-R46): Introduced new constants `ReservedAddress`, `LocalIpv6Address`, and `LocalAddress` to represent common network addresses.
* [`core/util/netutils.go`](diffhunk://#diff-3fa3772b0e7ad87ab2978e874a2324cafde5cedf6d5f4e6b810520f1b44a4320L176-R185): Replaced hardcoded address strings with the newly defined constants in …
=> refactor: const for ip zero or loopback address

docs/content.en/docs/release-notes/_index.md, lib/status/path.go
This pull request includes changes to the `lib/status/path.go` file to improve error handling and code readability. The most important changes include reordering imports and modifying the `DirSize` function to handle errors more gracefully.
Improvements to error handling and code readability:
* [`lib/status/path.go`](diffhunk://#diff-ee7113bebdbeff52f1a98a8291584f8af19b01798d158a6c4217d7e9776b2656L8-R15): Reordered imports to follow Go conventions.
* [`lib/status/path.go`](diffhunk://#diff-ee7113bebdbeff52f1a98a8291584f8af19b01798d158a6c4217d7e9776b2656L36-R51): Modified the `DirSize` function to continue walking the directory and ignore errors for non-root paths, improving robustness.
=> chore: fix path walk warn when tmp rename

docs/content.en/docs/release-notes/_index.md, modules/queue/disk_queue/consumer.go, modules/queue/disk_queue/diskqueue.go, modules/queue/disk_queue/module.go, plugins/queue/consumer/consumer.go
This pull request includes several changes to improve error handling and add new checks in the disk queue consumer module. The most important changes include fixing a bug related to the consumer segment, adding checks for the reader and empty queues, and enhancing error logging.
* [`docs/content.en/docs/release-notes/_index.md`](diffhunk://#diff-6a5ab1b382c7b8d732e1667c4b8b236b020871d8f02badb577c84a938e5826f5R20): Fixed consumer segment without producer issue.
* [`modules/queue/disk_queue/consumer.go`](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b2ba2R145-R148): Added a check to ensure the reader is not nil before reading the message size.
* [`modules/queue/disk_queue/consumer.go`](diffhunk://#diff-573abe7a34449f57e713a221e96c5b596978db9dc1e30804b808b3670f6b …
=> fix: comsumer segment without producer

docs/content.en/docs/release-notes/_index.md, modules/elastic/metadata.go
This pull request includes a change to the `clusterHealthCheck` function in the `modules/elastic/metadata.go` file. The change introduces an additional condition to the health check logic.
Modification to health check logic:
* [`modules/elastic/metadata.go`](diffhunk://#diff-f544072235bcb59af61377c05c77fd5adf657a7e7c2e666d8103901c220324f6L80-R80): Added a `force` parameter check to the condition that updates the cluster health status. This ensures that the health status is updated even if the cluster is available but the `force` parameter is set to true.
(#81)
=> fix: cluster init status loss when default setting is green

core/api/options.go, docs/content.en/docs/release-notes/_index.md
How to add your feature like this:
```
package filter
import (
log "github.com/cihub/seelog"
"infini.sh/framework/core/api"
httprouter "infini.sh/framework/core/api/router"
"net/http"
)
func init() {
api.RegisterUIFilter(&XXXFilter{})
}
type XXXFilter struct {
api.Handler
}
func (f *XXXFilter) GetPriority() int {
return 100
}
const FeatureXXX = "feature_XXXX"
func (f *XXXFilter) ApplyFilter(
method string,
pattern string,
options *api.HandlerOptions,
next httprouter.Handle,
) httprouter.Handle {
//option not enabled
if options == nil || !options.Feature(FeatureXXX) {
log.Debug(method, ",", pattern, ",skip feature xxx")
return next
}
return func(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
//APPLY your filter here
next(w, r, ps)
}
}
```
Assign this feature to specify …
=> chore: add util to access api feature option

app.go, docs/content.en/docs/release-notes/_index.md
This pull request includes a small but important change to the `app.go` file. The change modifies the service restart policy to ensure the service always restarts regardless of the exit status.
* [`app.go`](diffhunk://#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dL572-R572): Changed the `svcOptions["Restart"]` value from `"on-success"` to `"always"` to ensure the service restarts under all circumstances.
=> chore: set service restart policy to always

docs/content.en/docs/release-notes/_index.md, modules/elastic/metadata.go
This pull request includes updates to the release notes and a bug fix in the `ElasticModule`'s cluster health check function. The most important changes include adding a new bug fix entry to the release notes and refining the conditions for updating the cluster health status in the `ElasticModule`.
Updates to release notes:
* [`docs/content.en/docs/release-notes/_index.md`](diffhunk://#diff-6a5ab1b382c7b8d732e1667c4b8b236b020871d8f02badb577c84a938e5826f5L18-R22): Added a new bug fix entry to register cluster status loss when the default setting is `green`.
Bug fix in cluster health check:
* [`modules/elastic/metadata.go`](diffhunk://#diff-f544072235bcb59af61377c05c77fd5adf657a7e7c2e666d8103901c220324f6L80-R80): Refined the condition to update the cluster health status by checking if …
=> fix: register cluster status loss when default setting is `green`

modules/metrics/elastic/elasticsearch.go, modules/queue/disk_queue/diskqueue.go, modules/queue/disk_queue/module.go
This pull request improves error handling and logging in the `ElasticsearchMetric` and `DiskQueue` modules, as well as updates a configuration parameter in the `DiskQueue` module. The changes enhance debugging capabilities and make the system more robust against errors.
* [`modules/metrics/elastic/elasticsearch.go`](diffhunk://#diff-22f447a825424b74a7703ccf0b4e3f28778acd718ecb86664db68db3e1b9718aL220-R220): Enhanced error logging in `InitialCollectTask` by adding more descriptive messages for cluster health and state collection errors. [[1]](diffhunk://#diff-22f447a825424b74a7703ccf0b4e3f28778acd718ecb86664db68db3e1b9718aL220-R220) [[2]](diffhunk://#diff-22f447a825424b74a7703ccf0b4e3f28778acd718ecb86664db68db3e1b9718aL244-R244)
* …
=> chore: add detailed logging to `DiskQueue` for better traceability

.github/workflows/integration-test.yml, .github/workflows/unit_test.yml, Makefile
This pull request introduces several updates and enhancements to the `Makefile`, focusing on improving build configurations, adding support for new platforms, and refining development workflows. The most significant changes include replacing hardcoded paths with environment variables, adding new build targets for multiple architectures, and introducing `test` and `lint` commands for better code quality checks.
* Replaced hardcoded paths like `~/go` and `~/vfs` with the `$(HOME)` environment variable for better portability. (`[[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L26-R26)`, `[[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L39-R43)`)
* Added new build targets for Linux (`armv6`, `armv7`, `mips64`, …
=> chore: change makefile for ci task

Makefile
This pull request introduces changes to the `Makefile` to enhance build configurations by adding new debug build targets and refining existing development build targets. The most important changes focus on improving the flexibility and clarity of the build process for different environments and purposes.
* **Added a new debug build configuration (`GOBUILDDBG`)**: Introduced a new build command with debug-specific flags (`-N -l`) for better debugging support. This replaces the previous `GOBUILDDEV` configuration for debug purposes. (`Makefile`, [MakefileL80-R80](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L80-R80))
* **Added new debug build targets**: Introduced `build-debug`, `build-linux-amd64-debug`, and `build-linux-arm64-debug` targets to generate …
=> chore: refined development build

docs/content.en/docs/release-notes/_index.md, plugins/smtp/smtp.go
support custom TLS minimum version for SMTP processor configuration
=> feat: support custom TLS minimum version for SMTP processor configuration

app.go, modules/queue/disk_queue/module.go
This pull request introduces logging improvements and a new capacity check to enhance application monitoring and reliability. The changes focus on providing more detailed runtime information and ensuring proper resource allocation.
* Added a log statement in `app.go` to display the data directory being used by the application during initialization. This helps in debugging and understanding the runtime environment. (`[app.goR312](diffhunk://#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR312)`)
* Introduced a capacity check in `module.go` for the `DiskQueue` module. The new `checkCapacity` function verifies resource availability before starting the module, returning an error if the check fails. This ensures that the module operates within safe limits. …
=> chore: check capacity when disk queue module start

core/orm/orm.go, docs/content.en/docs/release-notes/_index.md
fix wrong method call during ORM update
=> fix: wrong method call during ORM update

docs/content.en/docs/release-notes/_index.md, lib/fasthttp/client.go, lib/fasthttp/http.go, lib/fasthttp/http_test.go, lib/fasthttp/streaming.go
=> fix: response without a body can't have trailers

core/config/system.go, core/model/basic_auth.go, modules/configs/client/client.go
add basic auth support to sync manager configuration
=> feat: add basic auth support to sync manager configuration

docs/content.en/docs/release-notes/_index.md, modules/elastic/schema.go, modules/elastic/schema_test.go
support underscore '_' in quoted JSON keys
=> fix: support underscore '_' in quoted JSON keys

core/elastic/search.go, core/orm/aggs.go, core/orm/aggs_args_parser.go, core/orm/aggs_args_parser_test.go, core/orm/aggs_test.go, core/orm/query.go, core/orm/query_test.go, docs/content.en/docs/release-notes/_index.md, lib/cache/cache_test.go, lib/cache/layeredcache_test.go, modules/elastic/orm/aggs.go, modules/elastic/orm/aggs_test.go, modules/elastic/orm/query_dsl.go, modules/elastic/orm/query_dsl_test.go
This pull request introduces several enhancements and fixes to the ORM and Elasticsearch integration, focusing on improved query support, aggregation flexibility, and better compatibility with Elasticsearch APIs. The most significant changes include adding support for the `query_string` query type, extending pipeline aggregations, and refining date histogram interval handling.
**Query Enhancements**
* Added support for the `query_string` query type in the ORM, including the ability to specify fields and the default operator. This is reflected in both the core query logic and the associated tests. [[1]](diffhunk://#diff-ebb7889b112ada31833848599efde6aa9529009602a63633bf6fae0e555a49b8R54) [[2]](diffhunk://#diff-ebb7889b112ada31833848599efde6aa9529009602a63633bf6fae0e555a49b8R340-R345) …
=> feat: add support for query_string query

docs/content.en/docs/release-notes/_index.md, plugins/elastic/indexing_merge/indexing_merge.go
This pull request adds support for customizing the write operation type in the `indexing_merge` processor for Elasticsearch. This allows users to specify whether documents should be created, indexed, or updated during bulk operations, increasing flexibility for different use cases.
Enhancements to indexing_merge processor:
* Added a new `WriteOpType` configuration field to the `Config` struct in `indexing_merge.go`, allowing users to specify the write operation type (e.g., `create`, `index`, `update`).
* Modified the document construction logic to use the configured `WriteOpType` instead of always defaulting to `index`. If not specified, it defaults to `index` for backward compatibility.
Documentation updates:
* Updated the release notes to mention support for custom write operation type …
=> feat: support custom write operation type for indexing_merge processor
