infinilabs/framework

modules/elastic/metadata.go
fixed node id, index id of elastic cluster metadata
=> chore: fixed node id of elastic metadata

modules/metrics/elastic/elasticsearch.go
Cluster-level isolation of collecting metrics
=> chore: optimize ES metric collecting

core/elastic/domain_actions.go, modules/elastic/metadata.go, modules/metrics/elastic/elasticsearch.go, modules/metrics/metrics.go
- splitting metric collecting task to cluster_health, cluster_stats, index_stats, node_stats collecting task for single cluster
- adding index health metric
- adding metadata change event callback
=> chore: splitting metric collecting task

modules/elastic/metadata.go
fix cluster health change callback was not triggered
=> fix: cluster health change callback was not triggered

core/util/webhunter.go
fixed nil pointer error when failed to create http request
=> fix: return error after failed to create http request

.github/workflows/build-docs.yml, docs/content.en/docs/release-notes/_index.md
=> feat: validate version branch, add product_name to commit message

docs/content.en/docs/release-notes/_index.md, modules/metrics/elastic/elasticsearch.go
clean unused code 
add `singleton` config to metrics task
=> chore: clean unused code and add `singleton` config to metrics task

docs/content.en/docs/release-notes/_index.md, modules/elastic/metadata.go
updating elastic metadata safely
=> fix: updating elastic metadata safely

Makefile, app.go, core/env/env.go, core/env/version.go, docs/content.en/docs/release-notes/_index.md, modules/api/api.go
Address and Closes https://github.com/infinilabs/framework/issues/14
=> chore: add commit hashes for framework and managed vendor dependencies

core/elastic/actions.go
=> chore: update logging message

docs/content.en/docs/release-notes/_index.md, plugins/badger/badger.go
=> chore: auto init the badger db for the first time access

docs/content.en/docs/release-notes/_index.md, modules/elastic/adapter/elasticsearch/v0.go
=> chore: add search response to logging message

core/elastic/domain_actions.go, docs/content.en/docs/release-notes/_index.md, modules/metrics/metrics.go
fix issue with metric collection task interval not working
=> fix: issue with metric collection task interval not working

modules/elastic/module.go
=> chore: update error logging message

.gitignore
=> chore: update git ignore file pattern

docs/content.en/docs/references/makefile.md
=> chore: update makefile docs

core/conditions/conditions.go, core/conditions/length.go, core/conditions/length_test.go, docs/content.en/docs/release-notes/_index.md
Closes: https://github.com/infinilabs/loadgen/issues/7
=> feat: add new condition to check item length (eg: array,string)

docs/content.en/docs/release-notes/_index.md, modules/api/api.go, modules/elastic/metadata.go
Fixed incorrect system cluster health status in the health API
=> fix:  system cluster health status in health api

docs/content.en/docs/release-notes/_index.md, modules/elastic/metadata.go
rollback metadata update using copy mechanism
=> chore: rollback metadata update using copy mechanism

core/env/env.go
fix incorrect framework vendor hash, related PR #19
=> fix: incorrect framework vendor hash

core/api/websocket/hub.go, docs/content.en/docs/release-notes/_index.md
=> chore: update WebSocket greeting message header to use

core/global/register.go, core/util/netutils.go
=> chore: downgrading noise loggging messages

core/api/handler.go, docs/content.en/docs/release-notes/_index.md
=> feat: add util to http handler, support to parse bool parameter

core/elastic/bulk_parser.go, core/elastic/bulk_parser_test.go, core/elastic/bulk_processor.go, core/elastic/bulk_processors_test.go, core/elastic/domain_actions.go, docs/content.en/docs/release-notes/_index.md, plugins/elastic/bulk_indexing/bulk_indexing.go
=> chore: handle simplified bulk metdata, parse index from url path

plugins/badger/badger.go
fix value log GC issue with Badger DB in multi-bucket mode
=> fix:  value log GC issue with Badger DB in multi-bucket mode

core/api/recovery.go, core/elastic/domain_actions.go, modules/elastic/orm.go, modules/pipeline/pipeline.go
=> chore: update search template data structure

.github/workflows/data/console-initialize.dsl, .github/workflows/data/loadgen_yml, .github/workflows/data/metrics-search.dsl, .github/workflows/data/runtime-registry.dsl, .github/workflows/integration-test.yml
This pull request introduces a new GitHub Actions workflow to run integration tests on pull requests to the main branch. The workflow sets up the necessary environments and dependencies, checks out multiple repositories, and compiles the code.
New GitHub Actions workflow:
* [`.github/workflows/integration-test.yml`](diffhunk://#diff-65ae1168eecd2c82b28b52c8a2c70866716e326bfa781144b33f0d74909103d9R1-R87): Added a new workflow named "Smoking Test" to run on pull requests to the main branch. This workflow sets up the git configuration, checks out the current repository and related repositories (`console`, `gateway`, `agent`, `framework-vendor`), sets up Node.js and Go toolchains, and compiles the code.
=> test: products integration test

docs/content.en/docs/release-notes/_index.md
=> docs: update release notes for v1.1.1

docs/content.en/docs/release-notes/_index.md, modules/metrics/elastic/elasticsearch.go
Fix incorrect interval configuration in index stats collection task
=> fix: incorrect interval configuration in index stats collection task

modules/metrics/elastic/elasticsearch.go
This pull request includes changes to improve error handling in the `CollectClusterHealth` and `CollectClusterState` functions in the `modules/metrics/elastic/elasticsearch.go` file. The most important changes involve explicitly handling context deadline exceeded errors.
Error handling improvements:
* [`modules/metrics/elastic/elasticsearch.go`](diffhunk://#diff-22f447a825424b74a7703ccf0b4e3f28778acd718ecb86664db68db3e1b9718aL507-R513): Modified the `CollectClusterHealth` function to explicitly handle context deadline exceeded errors and provide a more informative error message.
* [`modules/metrics/elastic/elasticsearch.go`](diffhunk://#diff-22f447a825424b74a7703ccf0b4e3f28778acd718ecb86664db68db3e1b9718aL580-R591): Modified the `CollectClusterState` function to explicitly handle context …
=> chore: improve the metrics collect error log

docs/content.en/docs/release-notes/_index.md
=> chore: update release notes for v1.1.2

app.go, core/global/register.go, docs/content.en/docs/release-notes/_index.md
=> feat: allow to register function before call setup

core/api/handler.go, docs/content.en/docs/release-notes/_index.md
=> chore: structure http error response

core/util/secured_json.go, core/util/secured_json_test.go, docs/content.en/docs/release-notes/_index.md
=> feat: add utility to securely marshal JSON

core/api/websocket/conn.go, core/api/websocket/hub.go, docs/content.en/docs/release-notes/_index.md
=> chore: introduce system type to echo welcome message in websocket

.gitignore, modules/elastic/orm.go, modules/queue/disk_queue/consumer.go
=> chore: misc changes

modules/metrics/metrics.go
misc change log level to trace
=> chore: change log level to trace

docs/content.en/docs/release-notes/_index.md
This PR updates the release notes.
=> chore: update release notes for publish 1.1.3

docs/content.en/docs/release-notes/_index.md
This PR updates the release notes.
=> chore: update release notes template for next publish

core/api/websocket/conn.go, core/api/websocket/hub.go, core/config/system.go, docs/content.en/docs/release-notes/_index.md
=> feat: add configuration option to disable echo messages during WebSocket connection

core/task/task.go, docs/content.en/docs/release-notes/_index.md
=> fix: task should be cancel on stop

core/api/api.go, core/api/common/config.go, core/api/handler.go, core/api/options.go, core/api/web.go, modules/web/web.go
This pull request includes several changes to the `core/api` package, focusing on refactoring authentication handling, adding new handler options, and introducing UI filters. The most important changes include moving authentication logic to a new `common` package, adding a registry for handler options, and implementing a filter mechanism for UI handlers.
* [`core/api/api.go`](diffhunk://#diff-5faa80368fcb83f22034d90a836248ce73eb18a7c87d51c9725f887578428e9aL72-R77): Moved the `EnableAuth` and `IsAuthEnable` functions to the new `common` package to centralize authentication logic. [[1]](diffhunk://#diff-5faa80368fcb83f22034d90a836248ce73eb18a7c87d51c9725f887578428e9aL72-R77) [[2]](diffhunk://#diff-660672ba1de86f6b7436c2ebf5bdc663c0675b88b6f50b1dcac54a53bebccb78L54-R55)
* …
=> feat: allow to register filters to ui handler

core/api/options.go, docs/content.en/docs/release-notes/_index.md
=> feat: add optional login flag

core/api/websocket/conn.go, core/orm/orm.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/orm.go
=> refactor: close websocket on callback error

docs/content.en/docs/release-notes/_index.md
This PR updates the release notes.
=> chore: update release notes for publish 1.1.4

core/task/task.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/schema.go, modules/metrics/elastic/elasticsearch.go, modules/redis/redis_queue.go
=> chore: misc fixes

core/api/api.go, core/api/client.go, core/api/common/config.go, core/api/options.go, core/api/recovery.go, core/api/web.go, core/api/websocket/conn.go, core/api/websocket/hub.go, core/task/task.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/adapter/elasticsearch/v7.go, modules/elastic/store.go, modules/pipeline/pipeline.go, plugins/badger/api.go
=> chore: lower priority filter should execute first

core/api/options.go, docs/content.en/docs/release-notes/_index.md
=> chore: refactory permission options to array

core/util/stringutil.go
https://github.com/infinilabs/gateway/issues/85
=> chore: add support for converting floats in InterfaceToInt

core/api/client.go, core/api/handler.go, core/api/options.go, core/config/oauth.go, core/config/system.go, core/env/env.go, core/security/access_token.go, core/security/action.go, core/security/const.go, core/security/permission.go, core/security/permission_change_signal.go, core/security/permission_registry.go, core/security/role_registry.go, core/security/user_claims.go, core/security/user_context.go, core/security/user_permission.go, core/security/user_profile.go, core/util/stringutil.go, docs/content.en/docs/release-notes/_index.md, modules/web/web.go
=> feat: general pluggable security feature

core/api/cors.go, core/api/handler.go, core/api/web.go, core/config/system.go, core/env/env.go, core/security/access_token.go, core/util/stringutil.go, docs/content.en/docs/release-notes/_index.md
=> feat: add cors settings to UI handler

core/api/websocket/conn.go, core/api/websocket/hub.go, plugins/stats_statsd/statsd.go
=> chore: remove unnecessary lock

core/api/options.go, docs/content.en/docs/release-notes/_index.md
=> chore: update api labels to support interface

docs/content.en/docs/release-notes/_index.md
This PR updates the release notes.
=> chore: update release notes for publish 1.1.5

core/elastic/index.go, core/orm/orm.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/orm.go
=> feat: add query query_string and prefix support to orm module

core/api/handler.go, core/env/env.go, docs/content.en/docs/release-notes/_index.md
=> fix: fix WriteHeader to prevent duplicate status code writes

core/api/session.go, docs/content.en/docs/release-notes/_index.md
=> chore: add util to delete session key

app.go, core/global/register.go, docs/content.en/docs/release-notes/_index.md
=> feat: allow to callback after setup

core/config/oauth.go, core/security/user_profile.go, docs/content.en/docs/release-notes/_index.md
=> chore: update profile structs

core/pipeline/config.go, docs/content.en/docs/release-notes/_index.md, modules/pipeline/pipeline.go, plugins/http/http.go
This pull request includes multiple changes to improve the functionality and performance of the HTTP processor in the pipeline. The most important changes include adding gzip compression support, refactoring code for better readability, and updating logging for better traceability.
* Added support for gzip compression with a configurable threshold in the `HTTPProcessor` configuration. (`plugins/http/http.go`) [[1]](diffhunk://#diff-c7a91ad19ebbf1d2e1799621a9a3b23da203adfe82baf4d15a32a2abcdce71fcR53-R61) [[2]](diffhunk://#diff-c7a91ad19ebbf1d2e1799621a9a3b23da203adfe82baf4d15a32a2abcdce71fcR79-R81) [[3]](diffhunk://#diff-c7a91ad19ebbf1d2e1799621a9a3b23da203adfe82baf4d15a32a2abcdce71fcR114-R115) [[4]](diffhunk://#diff-c7a91ad19ebbf1d2e1799621a9a3b23da203adfe82baf4d15a32a2abcdce71fcR124) …
=> feat: add compression support to HTTP processor

core/api/handler.go, core/api/session.go, docs/content.en/docs/release-notes/_index.md
=> chore: add util to write response for record not found

docs/content.en/docs/release-notes/_index.md, modules/elastic/adapter/elasticsearch/v9.go, modules/elastic/common/config.go
=> chore: add adaptor for elasticsearch v9

modules/api/api.go
=> chore: add info api to ui module, need login to access

docs/content.en/docs/release-notes/_index.md
This PR create by  to updates the release notes.
=> chore: update release notes for publish 1.1.6

docs/content.en/docs/release-notes/_index.md, modules/queue/disk_queue/module.go
=> feat: introduce config to check_capacity retry threshold limit

core/conditions/conditions.go, plugins/smtp/smtp.go
=> chore: refactoring fasttemplate

core/elastic/index.go, core/orm/mapper.go, core/orm/orm.go, docs/content.en/docs/release-notes/_index.md, modules/api/api.go, modules/elastic/orm.go
=> refactor: refactoring orm struct mapping and search api

core/orm/mapper.go, core/orm/mapper_test.go, core/orm/orm.go, docs/content.en/docs/release-notes/_index.md
=> refactor: refactoring orm module

docs/content.en/docs/release-notes/_index.md
This PR create by  to updates the release notes.
=> chore: update release notes for publish 1.1.7

.licensure.yml, core/conditions/conditions.go, core/elastic/index.go, core/orm/orm.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/orm.go, modules/queue/disk_queue/module.go, plugins/smtp/smtp.go
=> feat: add filter to orm query

core/elastic/index.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/adapter/elasticsearch/v0.go, modules/elastic/adapter/elasticsearch/v7.go, modules/elastic/orm.go
=> fix: add missing score field, fix filter

core/util/input_filter.go, core/util/input_filter_test.go, docs/content.en/docs/release-notes/_index.md
=> feat: add util to filter user's input

core/config/oauth.go
add json tag for struct OAuthConfig
=> chore: add json tag for struct OAuthConfig

core/orm/context.go, core/orm/context_test.go, core/orm/filter.go, core/orm/orm.go, core/orm/orm_legacy.go, core/orm/query.go, core/orm/query_args_parser.go, core/orm/query_args_parser_test.go, core/orm/query_test.go, core/orm/registry.go, core/param/parameter.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/orm.go, modules/elastic/orm/query_dsl.go, modules/elastic/orm/query_dsl_test.go, modules/elastic/orm/refresh.go, modules/elastic/schema.go
=> refactor: refactoring orm query

docs/content.en/docs/release-notes/_index.md
This PR create by github actions to updates the release notes.
=> chore: update release notes for publish 1.1.9

core/orm/query.go, core/orm/query_args_parser.go, core/orm/query_args_parser_test.go, docs/content.en/docs/references/query_url.md, docs/content.en/docs/release-notes/_index.md
=> feat: url query support terms query

core/orm/context.go, core/orm/context_test.go, core/orm/orm.go, core/orm/orm_test.go, core/orm/registry.go, core/security/user_context.go, core/security/user_profile.go, core/security/user_session.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/orm.go, modules/elastic/orm_test.go, modules/elastic/schema.go
=> feat: add hooks for ORM data operation

modules/elastic/orm.go
optimize log output for lower noise
=> chore: optimize log output for lower noise

core/api/session.go
=> chore: keep minimum config for cookie session

core/api/session.go, docs/content.en/docs/release-notes/_index.md
=> chore: less logging for session store change

core/util/stringutil.go, core/util/stringutil_test.go, docs/content.en/docs/release-notes/_index.md
add generate secure string util func
=> chore: add generate secure string util func

core/util/stringutil.go, core/util/stringutil_test.go, docs/content.en/docs/release-notes/_index.md
=> chore: add validate secure func

core/elastic/api.go, core/orm/registry.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/adapter/elasticsearch/v0.go, modules/elastic/adapter/elasticsearch/v5.go, modules/elastic/adapter/elasticsearch/v6.go, modules/elastic/adapter/elasticsearch/v7.go, modules/elastic/schema.go
=> refactor: initialize index schema using index template

modules/elastic/schema.go
=> chore: remove duplicatd index prefix

docs/content.en/docs/release-notes/_index.md, modules/elastic/metadata.go
=> fix: cluster metadata lost

core/api/web.go, docs/content.en/docs/release-notes/_index.md
=> chore: add util to register http handler

core/elastic/api.go, core/elastic/domain.go, docs/content.en/docs/release-notes/_index.md, modules/elastic/adapter/elasticsearch/v0.go
=> feat: add support for Elasticsearch cat allocation API

core/api/handler.go, docs/content.en/docs/release-notes/_index.md
=> feat: allow to read http request body multi-times
